
name: Flutter CI Test

on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
  steps:
  - uses: actions/checkout@v2
  - uses: subosito/flutter-action@v1.5.3
  - run: flutter pub get
  - run: flutter test
